[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.. && yarn run build"
  functions = "functions"
 
[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
  

[dev]
  publish = "exampleSite"
  command = "cd exampleSite && hugo server --themesDir ../.. --disableFastRender && cd .."
  
  
[dev.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"